credentials:
  usernames:
    admin:
      email: alapmehta2010@gmail.com
      name: Admin User
      password: 'Premilain901'  # Replace with your hashed admin password


preauthorized:
  emails:
    - alapmehta2010@gmail.com
