# config.yaml

# OAuth configuration
client_id: "389176055982-anmjh9i1ev0jb922bovs7o4qu6is8kpm.apps.googleusercontent.com"
client_secret: "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"
redirect_uri: "https://events-ulozygjxpzydwoqs2dczf8.streamlit.app"

# Cookie configuration for session management
cookie:
  expiry_days: 30
  key: "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"
  name: "streamlit_oauth_cookie"

# Preauthorized emails for login
preauthorized:
  emails:
    - alapmehta2010@gmail.com
    - user2@example.com
